### ISSUE TITLE
404 Error after User Login

### ISSUE THREAD

**Issue by zmayyem** [scrisoft/crm_chatbot#1]
Hello @scrisoft ,
First Thanks for releasing this project,

So after installing Midrub CMS and the User Theme + The CRM Addon + CRM Chatbot
When I try to login as Normal User I got Error 404 No Page was found , Even when I set the App 
redirection to the CRM Chat Bot , it redirect me to 404 Page 
Please see the screenshot below to understand me :

https://ibb.co/PtVDMPs

is the problem could be from the User Theme ?? can you please help to resolve it ??

PS , I installed the project on subdomain , it may be the Problem ??

Thanks in advance

**Comment by scrisoft** [comment]
Hi,

Configure correctly the plans. Ensure there is a redirect to an app.
